# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ClientDiscoveryResponse(Model):
    """List of available operations.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar value: List of available operationss.
    :vartype value: list of :class:`ClientDiscoveryValueForSingleApi
     <azure.mgmt.recoveryservices.models.ClientDiscoveryValueForSingleApi>`
    :ivar next_link: NextLink
    :vartype next_link: str
    """

    _validation = {
        'value': {'readonly': True},
        'next_link': {'readonly': True},
    }

    _attribute_map = {
        'value': {'key': 'Value', 'type': '[ClientDiscoveryValueForSingleApi]'},
        'next_link': {'key': 'NextLink', 'type': 'str'},
    }

    def __init__(self):
        self.value = None
        self.next_link = None
